/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.navaplay_studios.juego.sd;

/**
 *
 * @author alber
 */
public class PantallaCliente extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaCliente.class.getName());
    private Cliente cliente;
    /**
     * Creates new form PantallaCliente
     */
    public PantallaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonClose = new javax.swing.JButton();
        ButtonRock = new javax.swing.JButton();
        ButtonPaper = new javax.swing.JButton();
        ButtonScissors = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, -1));

        ButtonClose.setText("Cerrar conexiones");
        ButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCloseActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        ButtonRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/piedra.png"))); // NOI18N
        ButtonRock.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRockActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonRock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        ButtonPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/papel.png"))); // NOI18N
        ButtonPaper.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPaperActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        ButtonScissors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tijera.png"))); // NOI18N
        ButtonScissors.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonScissorsActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonScissors, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 240, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 390, 180));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 260, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setText("Introduza la IP del Servidor:");

        jTextField2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jTextField2.setText("192.168.1.68");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jButton1.setText("Conectarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCloseActionPerformed
        if (cliente != null) {
            cliente.cerrarConexion();
        }
        PantallaPrincipal pantalla = new PantallaPrincipal();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonCloseActionPerformed

    private void ButtonRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRockActionPerformed
        //Funcionalidad para el boton de piedra
        if (cliente != null && cliente.estaConectado()) {
            cliente.enviarJugada("R");
        }
    }//GEN-LAST:event_ButtonRockActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPanel1.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void ButtonScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonScissorsActionPerformed
        //Funcionalidad para el boton de tijera
        if (cliente != null && cliente.estaConectado()) {
            cliente.enviarJugada("T");
        }
    }//GEN-LAST:event_ButtonScissorsActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String textoIngresado = jTextField2.getText();

        // Crear cliente con callbacks
        cliente = new Cliente(
                textoIngresado,
                // Callback para mensajes
                mensaje -> {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        jTextArea1.append(mensaje + "\n");
                        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
                    });
                    if(mensaje.contains("Conectado como Jugador 1. Esperando segundo jugador...") && jLabel4!=null)
                        jLabel4.setText("Tu eres Jugador 1");
                    if(mensaje.contains("Conectado como Jugador 2. ¡El juego puede comenzar!") && jLabel4!=null)
                        jLabel4.setText("Tu eres Jugador 2");
                },
                // Callback para habilitar/deshabilitar botones
                habilitar -> {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        ButtonRock.setEnabled(habilitar);
                        ButtonPaper.setEnabled(habilitar);
                        ButtonScissors.setEnabled(habilitar);
                    });
                }
        );

        if (cliente.conectarServidor()) {
            jPanel2.setVisible(false);
            jPanel1.setVisible(true);
            jLabel3.setText("Conexión con el servidor: " + textoIngresado);
            // Los botones se habilitarán automáticamente cuando el servidor lo indique
            ButtonRock.setEnabled(false);
            ButtonPaper.setEnabled(false);
            ButtonScissors.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPaperActionPerformed
        //Funcionalidad para el boton de papel
        if (cliente != null && cliente.estaConectado()) {
            cliente.enviarJugada("P");
        }
    }//GEN-LAST:event_ButtonPaperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClose;
    private javax.swing.JButton ButtonPaper;
    private javax.swing.JButton ButtonRock;
    private javax.swing.JButton ButtonScissors;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    void habilitarBotones(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
